// AUTO-GENERATED — DO NOT EDIT THIS FILE.
//
// Generated from github.com/kayushkin/noteboard @ 1b76c09d61c72f4e31fc4fbef17b5f7c6b79296e
// Source of truth: the Go types named in tygo.yaml.
// To regenerate: ./generate-ts.sh
//
// Any manual changes will be overwritten on the next generation run.

// Code generated by tygo. DO NOT EDIT.

//////////
// source: model.go

/**
 * ItemType values. `workspace` is an agent's durable working memory: a
 * timestamped markdown document a recurring job rewrites each run. It is a
 * distinct type rather than a tagged `note` on purpose — a workspace is
 * rewritten forever and must never be mistakable for work to do (the todo queue
 * has already been flooded once) nor clutter the notes list. Being a type also
 * lets the schema enforce one workspace per job, which a convention cannot.
 */
export const TypeNote = "note";
/**
 * ItemType values. `workspace` is an agent's durable working memory: a
 * timestamped markdown document a recurring job rewrites each run. It is a
 * distinct type rather than a tagged `note` on purpose — a workspace is
 * rewritten forever and must never be mistakable for work to do (the todo queue
 * has already been flooded once) nor clutter the notes list. Being a type also
 * lets the schema enforce one workspace per job, which a convention cannot.
 */
export const TypeTodo = "todo";
/**
 * ItemType values. `workspace` is an agent's durable working memory: a
 * timestamped markdown document a recurring job rewrites each run. It is a
 * distinct type rather than a tagged `note` on purpose — a workspace is
 * rewritten forever and must never be mistakable for work to do (the todo queue
 * has already been flooded once) nor clutter the notes list. Being a type also
 * lets the schema enforce one workspace per job, which a convention cannot.
 */
export const TypeRank = "rank";
/**
 * ItemType values. `workspace` is an agent's durable working memory: a
 * timestamped markdown document a recurring job rewrites each run. It is a
 * distinct type rather than a tagged `note` on purpose — a workspace is
 * rewritten forever and must never be mistakable for work to do (the todo queue
 * has already been flooded once) nor clutter the notes list. Being a type also
 * lets the schema enforce one workspace per job, which a convention cannot.
 */
export const TypeWorkspace = "workspace";
export interface Item {
  id: string;
  type: string;
  title: string;
  body: string;
  tags: string[];
  priority: number /* int */;
  rank: number /* float64 */;
  status: string;
  list_id: string;
  due_at?: string;
  parent_id?: string;
  links: string[];
  /**
   * Schedule is the recurrence RULE (see schedule.go). DueAt above stays the
   * single source of truth for when this item is next due; Schedule is what
   * generates that answer, not a second copy of it.
   */
  schedule?: Schedule;
  /**
   * DeletedAt is the reversible delete. It is deliberately NOT the `archived`
   * status: archived is a state the user chose for a live item, deletion is
   * the item being taken away. Overloading one onto the other (which DELETE
   * used to do) means a restore cannot tell them apart.
   */
  deleted_at?: string;
  /**
   * HeldAt is the agent gate: work the user has parked. A held item stays
   * `open` and stays visible to humans — it is withheld from agent read paths,
   * which exclude held items by default (see db.ListParams.IncludeHeld).
   * Hold is deliberately NOT a `status`. Status is the work's lifecycle; hold
   * is who is allowed to act on it, and an item can legitimately be open AND
   * held. Collapsing them would hide parked work from the user's own open-todo
   * list, which is the opposite of what parking it means.
   * It is also deliberately not a kanban column. A column gates only the one
   * consumer that reads that column, so a card must be pausable in ANY stage
   * rather than only by being dragged into a designated gate column.
   */
  held_at?: string;
  hold_reason?: string;
  /**
   * AutoHoldAtUSD is the spend ceiling for this item: once the cumulative cost
   * of the agent sessions that worked it reaches this many dollars, it is held
   * automatically. Nil = no ceiling (the default; this is opt-in).
   * The dollars spent are deliberately NOT stored here. Cost lives in
   * llm-bridge's session aggregates and the item's session links are the join
   * — a copy kept on the item would be a second source of truth that goes stale
   * the moment a session bills another turn.
   * This one number drives two enforcement points, which is why it is one number:
   * the dispatcher hands the harness a per-session cap of (ceiling - already
   * spent), so no single session can push the item past the ceiling, and the
   * curator holds the item once the cumulative total reaches it. The per-session
   * cap is what makes the polled cumulative check safe: without it a fast burner
   * could blow far past the ceiling between two polls.
   */
  auto_hold_at_usd?: number /* float64 */;
  created_by: string;
  created_at: string;
  updated_at: string;
}
/**
 * Revision is the prior state of an item, snapshotted before every mutation.
 * Workspaces are rewritten on every job run, so an agent that corrupts its own
 * memory would otherwise destroy the accumulated judgment with no undo.
 */
export interface Revision {
  id: number /* int64 */;
  item_id: string;
  title: string;
  body: string;
  tags: string[];
  status: string;
  priority: number /* int */;
  list_id: string;
  parent_id?: string;
  links: string[];
  deleted_at?: string;
  /**
   * Reason names the mutation that produced this snapshot: update, delete,
   * or restore.
   */
  reason: string;
  replaced_at: string;
}
export interface CreateItemRequest {
  type: string;
  title: string;
  body?: string;
  tags?: string[];
  priority?: number /* int */;
  rank?: number /* float64 */;
  status?: string;
  list_id?: string;
  due_at?: string;
  parent_id?: string;
  links?: string[];
  schedule?: Schedule;
  created_by?: string;
  /**
   * Hold creates the item already parked, so there is no window between
   * creation and the gate closing in which an agent could pick it up. Opt-in:
   * the caller that knows the work is sensitive asks for it.
   */
  hold?: boolean;
  hold_reason?: string;
  /**
   * AutoHoldAtUSD arms the spend ceiling at creation. Nil = no ceiling.
   */
  auto_hold_at_usd?: number /* float64 */;
}
export interface UpdateItemRequest {
  title?: string;
  body?: string;
  tags?: string[];
  priority?: number /* int */;
  rank?: number /* float64 */;
  status?: string;
  list_id?: string;
  due_at?: string;
  parent_id?: string;
  links?: string[];
  schedule?: Schedule;
  /**
   * AutoHoldAtUSD is the spend ceiling. `null` clears it (see HasAutoHoldAtUSD).
   */
  auto_hold_at_usd?: number /* float64 */;
}
export type Alias = UpdateItemRequest;
export interface RerankRequest {
  items: RerankItem[];
}
export interface RerankItem {
  id: string;
  rank: number /* float64 */;
}
export interface ListInfo {
  list_id: string;
  count: number /* int */;
}
export interface TagInfo {
  tag: string;
  count: number /* int */;
}

//////////
// source: schedule.go

/**
 * Schedule is the recurrence rule for an item, expressed in RFC 5545 (iCalendar)
 * terms. It answers two independent questions that were previously conflated and
 * hardcoded into cron jobs:
 * 	when is this DUE      — DTStart + RRule + RDate - ExDate
 * 	when do I get NUDGED  — Remind.Lead (before due) and Remind.Nag (until done)
 * A task can have either, both, or neither. "Water the plants every 3rd Tuesday"
 * is a due recurrence with no nag. "Call the tag agency" is a one-shot due date
 * with a weekday nag until it is done. Those are different axes, so they are
 * different fields.
 * Schedule is the RULE. It is NOT the answer. Item.DueAt remains the single
 * source of truth for "when is this next due" — the coordinator expands the rule
 * and writes the resulting instant into DueAt (rolling mode) or into a freshly
 * materialized child item's DueAt (instance mode). DTStart is the ANCHOR of the
 * series, in the iCalendar sense: where the recurrence starts counting from and
 * what time of day it lands on. It is not "the next due date" and must never be
 * read as one.
 * RFC 5545 rather than a homemade cadence grammar because it already expresses
 * every case anyone asks for (every 3rd Tuesday: FREQ=MONTHLY;BYDAY=3TU; last
 * weekday of the month: FREQ=MONTHLY;BYDAY=MO,TU,WE,TH,FR;BYSETPOS=-1), and
 * because Google Calendar consumes it natively — so mirroring an item to the
 * calendar is a pass-through, not a translation that could disagree with us.
 */
export interface Schedule {
  /**
   * DTStart anchors the series: the first candidate instant, and the time of
   * day every occurrence inherits. Required whenever RRule is set.
   */
  dtstart?: string;
  /**
   * TZID is the IANA zone the rule is expanded in (e.g. "America/Los_Angeles").
   * Required whenever a rule is present, and deliberately NOT defaulted: an
   * offset is not a zone. A stored offset like -07:00 cannot tell you what
   * happens after a DST transition, so a rule anchored only to an offset
   * silently drifts by an hour twice a year — which is exactly the bug the cron
   * nudges this replaces have today. "9am on the 3rd Tuesday" means 9am local
   * in a named zone or it means nothing.
   */
  tzid?: string;
  /**
   * RRule is the recurrence, without the "RRULE:" prefix (though one is
   * tolerated): "FREQ=MONTHLY;BYDAY=3TU". Empty means the item is a one-shot.
   */
  rrule?: string;
  /**
   * RDate adds explicit one-off occurrences on top of RRule. An item with only
   * RDate and no RRule is "these specific dates and no others".
   * Applies to the DUE series only, never to Remind.Nag. Both used to be fed
   * into whichever rule was being expanded, so adding one extra due date also
   * bought an extra nag on that date — a rule the user never wrote.
   */
  rdate?: string[];
  /**
   * ExDate removes occurrences the rule would otherwise produce (a skipped
   * week). Due series only, on the same grounds as RDate.
   */
  exdate?: string[];
  /**
   * Mode decides what an occurrence MEANS. See ScheduleMode* below.
   */
  mode?: string;
  remind?: Remind;
  /**
   * LastMaterializedAt is the occurrence instant the coordinator has already
   * acted on. It is bookkeeping written by the coordinator, not by the user,
   * and it is what makes materialization idempotent: a coordinator run that
   * crashes and reruns, or a *\/15 tick that fires twice, must not produce two
   * child items for the same Tuesday.
   */
  last_materialized_at?: string;
  /**
   * LastNaggedAt is the last time this item's nag rule actually reached the
   * user. Same purpose, other axis: the coordinator ticks every 15 minutes, so
   * without it a single 10am firing would be re-sent on all 96 ticks of the day.
   */
  last_nagged_at?: string;
}
/**
 * ScheduleModeInstance materializes a child item per occurrence (via
 * ParentID). The scheduled item is a TEMPLATE: it never itself appears as
 * work, each occurrence is an ordinary independent todo, and completing one
 * week's does not touch the next. This keeps every consumer downstream dumb —
 * the digest just lists open todos and never needs to understand recurrence.
 */
export const ScheduleModeInstance = "instance";
/**
 * ScheduleModeRolling advances the item's own DueAt to the next occurrence
 * when it is completed. One row, no children, no completion history. Right
 * for "renew the registration annually", where last year's is of no interest.
 */
export const ScheduleModeRolling = "rolling";
/**
 * Channels a reminder can be delivered on. The digest is the primary surface and
 * is always available; calendar and herald are opt-in per item.
 */
export const ChannelDigest = "digest";
/**
 * Channels a reminder can be delivered on. The digest is the primary surface and
 * is always available; calendar and herald are opt-in per item.
 */
export const ChannelCalendar = "calendar";
/**
 * Channels a reminder can be delivered on. The digest is the primary surface and
 * is always available; calendar and herald are opt-in per item.
 */
export const ChannelHerald = "herald";
/**
 * Remind is how an item gets surfaced. Orthogonal to when it is due.
 */
export interface Remind {
  /**
   * Lead fires ahead of a due occurrence: ISO 8601 durations, negative for
   * "before" ("-P1D", "-PT2H"). Calendar-aware — "-P1D" is one calendar day,
   * not 24 hours, so it stays correct across a DST boundary.
   */
  lead?: string[];
  /**
   * Nag repeats until the item is done, independent of its due date. This is
   * the "keep bothering me" rule: FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR;BYHOUR=10.
   * It anchors on DTStart, or on the item's DueAt if DTStart is unset.
   */
  nag?: string;
  /**
   * Channels defaults to digest-only when empty.
   */
  channels?: string[];
}
/**
 * ISO8601Duration is a VALARM-style trigger offset: [-]P[nW][nD][T[nH][nM][nS]].
 * It is kept as a calendar quantity rather than collapsed into a time.Duration
 * because "one day before" and "24 hours before" are different questions on the
 * two days a year the clocks move.
 */
export interface ISO8601Duration {
  Negative: boolean;
  Weeks: number /* int */;
  Days: number /* int */;
  Hours: number /* int */;
  Minutes: number /* int */;
  Seconds: number /* int */;
}
